# Generated by Django 4.2.5 on 2023-09-22 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_system.question')),
            ],
        ),
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(blank=True, max_length=200)),
                ('sap_flg', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=200)),
                ('industry', models.CharField(blank=True, max_length=200)),
                ('cost_lower', models.CharField(blank=True, max_length=200)),
                ('cost_upper', models.CharField(blank=True, max_length=200)),
                ('settlement', models.CharField(blank=True, max_length=200)),
                ('role_overview', models.CharField(blank=True, max_length=200)),
                ('details', models.CharField(blank=True, max_length=200)),
                ('essential_skills', models.CharField(blank=True, max_length=200)),
                ('preferred_skills', models.CharField(blank=True, max_length=200)),
                ('age_limit', models.IntegerField(blank=True, null=True)),
                ('sales_restricions', models.CharField(blank=True, max_length=200)),
                ('english_skills', models.CharField(blank=True, max_length=200)),
                ('foreign_nationality', models.CharField(blank=True, max_length=200)),
                ('work_location', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('working_conditions', models.CharField(blank=True, max_length=200)),
                ('pic', models.CharField(blank=True, max_length=200)),
                ('contract_terms', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('registant', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updater', models.CharField(blank=True, max_length=200)),
                ('remarks', models.CharField(blank=True, max_length=200)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales_system.vendors')),
            ],
        ),
    ]
